name: CI Vulnerability Scans

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-app-vulnerability-scans.yml
  pull_request:
    paths:
      - app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-app-vulnerability-scans.yml

jobs:
  build-and-publish:
    name: Build and export cache
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: "app"
      ref: ${{ github.ref }}
    secrets: inherit

  vulnerability-scans:
    name: Vulnerability Scans
    needs: [build-and-publish]  # Wait for cache to be exported first
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: "app"
    secrets: inherit
